#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/gpfs/fs1/home/e/etayhay/frankm/.virtualenvs/alex_env/lib/python3.7/site-packages/neuron/.data"
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/gpfs/fs1/home/e/etayhay/frankm/.virtualenvs/alex_env/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/e/etayhay/frankm/Mazza2021/code/mod/x86_64/.libs/libnrnmech.so" "$@"
